#!/bin/bash

# Copyright (c) 2024 Gibson Pilconis, shibedrill, and contributors
# SPDX-License-Identifier: BSD-3-Clause

set -e

if command -V python3 &> /dev/null; then
    PYTHON=python3
elif command -V python &> /dev/null; then
    PYTHON=python
else
    echo Could not find a Python interpreter.
    exit 1 # error
fi

$PYTHON 'helper.py' $@
